// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package corpus

import (
	"context"
	"encoding/json"
	"time"

	"git.cana.pw/avalonbits/fball"
	"git.cana.pw/avalonbits/fball/db"
)

func (c Corpus) getFballCountryResponse(
	ctx context.Context, endpoint string, max int, rng db.Range, policy refreshPolicy,
	params db.URLQueryStringer) ([]fball.CountryResponse, error) {
	// Query the countries from the database.
	resp := []fball.CountryResponse{}
	err := c.handle.Query(ctx, endpoint, params, max, rng, func(data []byte) error {
		cr := fball.CountryResponse{}
		if err := json.Unmarshal(data, &cr); err != nil {
			return err
		}
		resp = append(resp, cr)
		return nil
	})

	if err == nil && len(resp) != 0 && rp_OneDay.Valid(time.Now(), resp[0].When()) {
		return resp, nil
	} else if err != nil {
		c.logger.Printf("WARNING - query error for countries: %v", err)
	}

	// Either the data is not available or it has expired.
	crQ := fball.CountryResponse{}
	if err := c.fballc.Get(ctx, endpoint, &crQ, params); err != nil {
		// We tolerate stale data if the api call fails. We still log it.
		if len(resp) != 0 {
			c.logger.Printf("WARNING - unable to query countries: %v.", err)
			c.logger.Printf("WARNING - returning stale data for countries.")
			return resp, nil
		} else {
			return nil, err
		}
	}

	if err := c.handle.Insert(ctx, endpoint, crQ, params); err != nil {
		c.logger.Printf("ERROR - unable to write country to cache: %v", err)
	}

	return []fball.CountryResponse{crQ}, nil
}

func (c Corpus) getFballTimezoneResponse(
	ctx context.Context, endpoint string, max int, rng db.Range, policy refreshPolicy,
	params db.URLQueryStringer) ([]fball.TimezoneResponse, error) {
	// Query the countries from the database.
	resp := []fball.TimezoneResponse{}
	err := c.handle.Query(ctx, endpoint, params, max, rng, func(data []byte) error {
		cr := fball.TimezoneResponse{}
		if err := json.Unmarshal(data, &cr); err != nil {
			return err
		}
		resp = append(resp, cr)
		return nil
	})

	if err == nil && len(resp) != 0 && rp_OneDay.Valid(time.Now(), resp[0].When()) {
		return resp, nil
	} else if err != nil {
		c.logger.Printf("WARNING - query error for countries: %v", err)
	}

	// Either the data is not available or it has expired.
	crQ := fball.TimezoneResponse{}
	if err := c.fballc.Get(ctx, endpoint, &crQ, params); err != nil {
		// We tolerate stale data if the api call fails. We still log it.
		if len(resp) != 0 {
			c.logger.Printf("WARNING - unable to query countries: %v.", err)
			c.logger.Printf("WARNING - returning stale data for countries.")
			return resp, nil
		} else {
			return nil, err
		}
	}

	if err := c.handle.Insert(ctx, endpoint, crQ, params); err != nil {
		c.logger.Printf("ERROR - unable to write country to cache: %v", err)
	}

	return []fball.TimezoneResponse{crQ}, nil
}
